# ============================================================
# Copyright (C) 2022 - Midden - All Rights Reserved
# ============================================================
#
# Maintainer: John White <john@midden.io>
# ============================================================

on: [workflow_call]

name: generate release build and publish crate

jobs:
  build-release-publish:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
