# ============================================================
# Copyright (C) 2022 - Midden - All Rights Reserved
# ============================================================
#
# Maintainer: John White <john@midden.io>
# ============================================================
name: generate release build and publish crate(s)

on: 
  workflow_call:
    inputs:
      crates:       
        description: 'crate to build and publish'
        required: true
        type: string
    secrets:
      REGISTRY_NAME:
        required: true
      REGISTRY_AUTH_TOKEN:
        required: true
      REGISTRY_INDEX:
        required: true

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
  publish-workspace-crates:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        crate_name: ${{ fromJson(inputs.crates) }}
    steps:
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: -p ${{ matrix.crate_name }} --index ${{ secrets.REGISTRY_INDEX }} --registry=${{ secrets.REGISTRY_NAME }} --config "http.user-agent=shipyard-rs ${{ secrets.REGISTRY_AUTH_TOKEN }}" --config "net.git-fetch-with-cli = true"
